import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Navbar} from "../components/navigation/navbar";
import {Footer} from "../components/navigation/footer";

import { useAuth0 } from '@auth0/auth0-react';
import useSWR from 'swr';

export default function Home() {

  const {
    user,
    isAuthenticated,
    isLoading,
    getAccessTokenSilently,
  } = useAuth0();

  const { data, error } = useSWR(
      isLoading || !isAuthenticated ? null : '/api/my/shows',
      async (url) => {
        const accessToken = await getAccessTokenSilently({
          audience: 'https://api/tv-shows',
          scope: 'read:shows',
        });
        const res = await fetch(url, {
          headers: {
            authorization: `Bearer ${accessToken}`,
          },
        });
        return res.json();
      }
  );

  if (isLoading) {
    return <div>Loading your user information...</div>;
  }

  if (!isAuthenticated) {
    return <div>
        You must first sign in to access your subscriptions.
    </div>;
  }

  if (error) {
    return <div>There was an error loading your subscriptions.</div>;
  }

  if (!data) {
    return (
        <div>
          <h1>Subscriptions for {user.email}</h1>
          <div>Loading your subscriptions ...</div>
        </div>
    );
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
          <Navbar />
          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Mon titre &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
                href="https://github.com/vercel/next.js/tree/master/examples"
                className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <Footer />
      </div>
  )
}
